engines:
  eslint:
    enabled: true
  duplication:
    enabled: false
    checks:
      Similar code:
        enabled: false
    config:
      languages:
        javascript:
          mass_threshold: 100
  exclude_paths:
    - server/tests/
    - node_modules/
    - bower_components/
    - template/public
    - coverage/