language: ruby
language: node_js
dist: trusty
sudo: false
node_js:
  - "6.10"
install:
  - npm install
script:
  - npm test
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
# In the case where travis is setup to build PR updates only,
  # uncomment the line below
  # - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT