language: node_js
branches:
  only:
    - master
node_js:
  - "6.10"
install:
  - npm install
script:
  - npm test
services:
  - postgresql
cache: 
  - npm install
before_script:
  - sequelize db:migrate
after_script: 
  - nyc npm test && nyc report --reporter=text-lcov | coveralls
after_success:
  - npm run coveralls
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=H9AhM6hCSE6BzPXk2XQRY420Ok1spAQ0f