language: node_js
dist: trusty
sudo: false
branches:
  only:
    - master
node_js:
  - "6.10"
install:
  - npm install
script:
  - npm test
service:
  - postgresql
# before_script:
#   - createuser postgres -s -U postgres
#   - createdb postit-dev --username=postgres
#   - sequelize db:migrate
after_script: NODE_ENV=test instanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
after_success: 
  - npm run coverage
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=H9AhM6hCSE6BzPXk2XQRY420Ok1spAQ0f